/*
 * This source file was generated by the Gradle 'init' task
 */
package labo06;

import java.util.*;

public class VideoJuego2 {
    public static void main(String[] args) {
        Random rand = new Random();
        ArrayList<ArrayList<Boolean>> casillasOcupadas = new ArrayList<>();
        ArrayList<ArrayList<Soldado>> soldados = new ArrayList<>();
        int numSoldados = rand.nextInt(10) + 1;
        ArrayList<String> ordenSoldados = new ArrayList<>();
        for(int i = 0;i<10;i++){
            casillasOcupadas.add(new ArrayList<Boolean>());
            soldados.add(new ArrayList<Soldado>());
            for(int j = 0;j<10;j++){
                casillasOcupadas.get(i).add(false);
                soldados.get(i).add(null);
            }
        }
        int count=0;
        do{
            int randColumn = rand.nextInt(10);
            int randRow = rand.nextInt(10);
            while(isFull(randRow,randColumn,casillasOcupadas)){
                randColumn = rand.nextInt(10);
                randRow = rand.nextInt(10);
            }
            casillasOcupadas.get(randRow).add(randColumn,true);
            soldados.get(randRow).add(randColumn,new Soldado("Soldado"+count,randRow,randColumn,rand.nextInt(5)+1));
            ordenSoldados.add(soldados.get(randRow).get(randColumn).getNombre());
            count++;
        }while(count<numSoldados);
        showBoard(casillasOcupadas);
        String mayorVida = findMaxLifeSoldier(soldados);
        System.out.print("Soldado de Mayor Vida: "+mayorVida);
        double promedioVida = calcularPromedioVida(soldados, numSoldados);
        int totalVida = calcularTotalVida(soldados);
        System.out.println("Promedio de nivel de vida: "+promedioVida);
        System.out.println("Total de vida del ejercito: "+totalVida);
        System.out.println("Soldados en el orden de creación");
        armyCreation(ordenSoldados,soldados);
        ArrayList<Soldado> soldadosFila = toUnidimensional(soldados);
        bubbleSortLife(soldadosFila);
        System.out.println("Ranking de poder (Bubble Sort):");
        showArmyInfo(soldadosFila);
        insertionSortLife(soldadosFila);
        System.out.println("Ranking de poder (Insertion Sort):");
        showArmyInfo(soldadosFila);
    }
    public static boolean isFull(int row, int column, ArrayList<ArrayList<Boolean>> casillasOcupadas) {
        return casillasOcupadas.get(row).get(column);
    }
    public static void showBoard(ArrayList<ArrayList<Boolean>> casillasOcupadas) {
        System.out.print("\t");
        for(int i = 0;i<10;i++){
            System.out.print((i+1)+"    ");
        }
        System.out.println();
        System.out.print("   ");
        for(int l = 0;l<12;l++){
            System.out.print("____");
        }
        System.out.println();
        for(int j = 0;j<10;j++){
            if(j!=9)
                System.out.print((j+1)+"  ");
            else
                System.out.print((j+1)+" ");
            for(int k = 0;k<10;k++){
                System.out.print("|");
                if(isFull(j,k,casillasOcupadas)){
                    System.out.print("+");
                }else{
                    System.out.print(" ");
                }
                System.out.print("|  ");
            }
            System.out.println();
            System.out.print("   ");
            for(int l = 0;l<12;l++){
                System.out.print("____");
            }
            System.out.println();
        }
    }
    public static void armyCreation(ArrayList<String> orden, ArrayList<ArrayList<Soldado>> ejercito) {
        for (String nombre : orden) {
            Soldado soldado = findSoldier(nombre, ejercito);
            if (soldado != null) {
                System.out.print(soldado.toString());
            }
        }
    }

    public static Soldado findSoldier(String nombre, ArrayList<ArrayList<Soldado>> ejercito) {
        for (ArrayList<Soldado> fila : ejercito) {
            for (Soldado soldado : fila) {
                if (soldado != null && nombre.equals(soldado.getNombre())) {
                    return soldado;
                }
            }
        }
        return null;
    }

    public static ArrayList<Soldado> toUnidimensional(ArrayList<ArrayList<Soldado>> soldados){
        ArrayList<Soldado> unidimensional = new ArrayList<>();
        for (ArrayList<Soldado> fila : soldados) {
            for (Soldado soldado : fila) {
                if (soldado != null) {
                    unidimensional.add(soldado);
                }
            }
        }
        return unidimensional;
    }
    public static void showArmyInfo(ArrayList<Soldado> ejercito) {
        for (Soldado soldado : ejercito) {
            if (soldado != null) {
                System.out.print(soldado);
            }
        }
    }
    public static int calcularTotalVida(ArrayList<ArrayList<Soldado>> soldados) {
        int totalVida = 0;
        for(ArrayList<Soldado> fila : soldados){
            for(Soldado soldado : fila){
                if(soldado!=null){
                    totalVida += soldado.getNivelVida();
                }
            }
        }
        return totalVida;
    }
    public static double calcularPromedioVida(ArrayList<ArrayList<Soldado>> soldados, int numSoldados) {
        int totalVida = calcularTotalVida(soldados);
        return (double) totalVida / numSoldados;
    }
    public static String findMaxLifeSoldier(ArrayList<ArrayList<Soldado>> soldados) {
        Soldado max = null;
        for (ArrayList<Soldado> fila : soldados) {
            for (Soldado soldado : fila) {
                if (soldado != null && (max == null || soldado.getNivelVida() > max.getNivelVida())) {
                    max = soldado;
                }
            }
        }
        return max.toString();
    }

    public static void insertionSortLife(ArrayList<Soldado> ejercito) {
        for (int i = 1; i < ejercito.size(); i++) {
            Soldado key = ejercito.get(i);
            int j = i - 1;

            while (j >= 0 && ejercito.get(j) != null && key != null && ejercito.get(j).getNivelVida() < key.getNivelVida()) {
                ejercito.set(j+1,ejercito.get(j));
                j = j - 1;
            }
            ejercito.set(j+1,key);
        }
    }

    public static void bubbleSortLife(ArrayList<Soldado> ejercito) {
        for (int i = 0; i < ejercito.size() - 1; i++) {
            for (int j = 0; j < ejercito.size() - 1 - i; j++) {
                if (ejercito.get(j) != null && ejercito.get(j+1) != null &&
                        ejercito.get(j).getNivelVida() < ejercito.get(j+1).getNivelVida()) {
                    Soldado temp = ejercito.get(j);
                    ejercito.set(j,ejercito.get(j+1));
                    ejercito.set(j+1,temp);
                }
            }
        }
    }
}
    